name: uitest
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.4
  flutter_vertical_marquee: ^0.2.1
  share: ^0.5.3
  flutter_redux: ^0.5.3 #redux
  fluwx: ^0.5.5 #微信
  dio: ^1.0.14 #网络框架
  event_bus: ^1.0.1 #事件订阅
  shared_preferences: ^0.5.1 #本地存储
  #card_settings: ^1.2.5 #卡片表单
  image_picker: ^0.6.0+3 #选择图片
  json_annotation: ^2.0.0
  flutter_webview_plugin: ^0.3.5 #网页浏览器
  cached_network_image: ^0.8.0
  jmessage_flutter: ^0.0.11 #极光IM
  url_launcher: ^4.0.3 #url唤起
  #flutter_qq_bridge: ^0.0.3 #QQ快捷
  pull_to_refresh: ^1.3.3 #下拉加载
  flutter_html: ^0.9.6 #富文本
  html: ^0.13.3 #富文本
  photo_view: ^0.4.0 #图片preview
  fluttertoast: ^3.0.4 #toast弹窗
  city_pickers: ^0.1.8 #城市联动
  image_jpeg: ^1.1.1 #图片压缩转jpeg

  #flutter_html_textview: ^0.2.6
  #flutter_html_view: ^0.2.6

dev_dependencies:
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data/province.json
    - images/  
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
